<x-layouts.app title="Journal Entries">

    <div class="mb-6">
        <div>
            <h1 class="text-2xl font-semibold text-gray-900">
                Journal Entries
            </h1>

            <p class="mt-1 text-sm text-gray-500">
                View all accounting entries generated by business transactions.
            </p>
        </div>
    </div>

    {{-- Filters --}}
    <div class="mb-5 rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
        <form method="GET"
              action="{{ route('journal-entries.index') }}"
              class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-5">

            <div class="lg:col-span-2">
                <label class="mb-1 block text-xs font-medium text-gray-600">
                    Search
                </label>

                <input
                    type="text"
                    name="search"
                    value="{{ request('search') }}"
                    placeholder="JE number or description"
                    class="w-full rounded-lg border-gray-300 text-sm focus:border-gray-900 focus:ring-gray-900"
                >
            </div>

            <div>
                <label class="mb-1 block text-xs font-medium text-gray-600">
                    From
                </label>

                <input
                    type="date"
                    name="date_from"
                    value="{{ request('date_from') }}"
                    class="w-full rounded-lg border-gray-300 text-sm focus:border-gray-900 focus:ring-gray-900"
                >
            </div>

            <div>
                <label class="mb-1 block text-xs font-medium text-gray-600">
                    To
                </label>

                <input
                    type="date"
                    name="date_to"
                    value="{{ request('date_to') }}"
                    class="w-full rounded-lg border-gray-300 text-sm focus:border-gray-900 focus:ring-gray-900"
                >
            </div>

            <div>
                <label class="mb-1 block text-xs font-medium text-gray-600">
                    Account
                </label>

                <select
                    name="account_id"
                    class="w-full rounded-lg border-gray-300 text-sm focus:border-gray-900 focus:ring-gray-900"
                >
                    <option value="">All accounts</option>

                    @foreach($accounts as $account)
                        <option
                            value="{{ $account->id }}"
                            @selected(request('account_id') == $account->id)
                        >
                            {{ $account->code }} - {{ $account->name }}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="flex items-end gap-2 lg:col-span-5">
                <button
                    type="submit"
                    class="inline-flex items-center rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-gray-800"
                >
                    <i class="bx bx-search mr-1.5"></i>
                    Search
                </button>

                <a
                    href="{{ route('journal-entries.index') }}"
                    class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50"
                >
                    Clear
                </a>
            </div>
        </form>
    </div>

    {{-- Entries --}}
    <div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">

        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">

                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                            Entry
                        </th>

                        <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                            Date
                        </th>

                        <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                            Description
                        </th>

                        <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                            Reference
                        </th>

                        <th class="px-5 py-3 text-right text-xs font-semibold uppercase tracking-wide text-gray-500">
                            Debit
                        </th>

                        <th class="px-5 py-3 text-right text-xs font-semibold uppercase tracking-wide text-gray-500">
                            Credit
                        </th>

                        <th class="px-5 py-3"></th>
                    </tr>
                </thead>

                <tbody class="divide-y divide-gray-100">

                    @forelse($entries as $entry)

                        <tr class="transition hover:bg-gray-50">

                            <td class="whitespace-nowrap px-5 py-4">
                                <a
                                    href="{{ route('journal-entries.show', $entry) }}"
                                    class="font-medium text-gray-900 hover:underline"
                                >
                                    {{ $entry->reference_no }}
                                </a>
                            </td>

                            <td class="whitespace-nowrap px-5 py-4 text-sm text-gray-600">
                                {{ $entry->entry_date->format('d M Y') }}
                            </td>

                            <td class="max-w-sm px-5 py-4">
                                <div class="truncate text-sm text-gray-700">
                                    {{ $entry->description ?: '—' }}
                                </div>
                            </td>

                            <td class="whitespace-nowrap px-5 py-4">
                                @if($entry->referenceUrl())

                                    <a
                                        href="{{ $entry->referenceUrl() }}"
                                        class="inline-flex items-center gap-1 rounded-md bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-700 hover:bg-gray-200"
                                    >
                                        <i class="bx bx-link-external"></i>
                                        {{ $entry->referenceLabel() }}
                                    </a>

                                @else
                                    <span class="text-sm text-gray-400">
                                        —
                                    </span>
                                @endif
                            </td>

                            <td class="whitespace-nowrap px-5 py-4 text-right text-sm font-medium text-gray-900">
                                {{ number_format($entry->lines_sum_debit, 2) }}
                            </td>

                            <td class="whitespace-nowrap px-5 py-4 text-right text-sm font-medium text-gray-900">
                                {{ number_format($entry->lines_sum_credit, 2) }}
                            </td>

                            <td class="whitespace-nowrap px-5 py-4 text-right">
                                <a
                                    href="{{ route('journal-entries.show', $entry) }}"
                                    class="inline-flex items-center justify-center rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900"
                                    title="View entry"
                                >
                                    <i class="bx bx-chevron-right text-lg"></i>
                                </a>
                            </td>

                        </tr>

                    @empty

                        <tr>
                            <td colspan="7" class="px-5 py-12 text-center">

                                <i class="bx bx-receipt text-4xl text-gray-300"></i>

                                <p class="mt-2 text-sm font-medium text-gray-700">
                                    No journal entries found.
                                </p>

                                <p class="mt-1 text-sm text-gray-500">
                                    Journal entries will appear here when accounting transactions are posted.
                                </p>

                            </td>
                        </tr>

                    @endforelse

                </tbody>

            </table>
        </div>

        @if($entries->hasPages())
            <div class="border-t border-gray-200 px-5 py-4">
                {{ $entries->links() }}
            </div>
        @endif

    </div>

</x-layouts.app>